package changes;

public enum StateChange {

	DO_NOTHING, ADD_ANNOTATION, REMOVE_ANNOTATION, CHANGE_BOUNDARIES, CHANGE_TYPE, ADD_ARGUMENT, REMOVE_ARGUMENT, CHANGE_ARGUMENT_ROLE, CHANGE_ARGUMENT_ENTITY;

}
